/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1EnvironmentSpecCompliance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1EnvironmentSpecCompliance{}

// ManagementV1alpha1EnvironmentSpecCompliance Compliance for the Environment.
type ManagementV1alpha1EnvironmentSpecCompliance struct {
	// Reference to Amplify Central design Ruleset
	Design *string `json:"design,omitempty"`
	// Reference to Amplify Central security Ruleset
	Security *string `json:"security,omitempty"`
}

// NewManagementV1alpha1EnvironmentSpecCompliance instantiates a new ManagementV1alpha1EnvironmentSpecCompliance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1EnvironmentSpecCompliance() *ManagementV1alpha1EnvironmentSpecCompliance {
	this := ManagementV1alpha1EnvironmentSpecCompliance{}
	return &this
}

// NewManagementV1alpha1EnvironmentSpecComplianceWithDefaults instantiates a new ManagementV1alpha1EnvironmentSpecCompliance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1EnvironmentSpecComplianceWithDefaults() *ManagementV1alpha1EnvironmentSpecCompliance {
	this := ManagementV1alpha1EnvironmentSpecCompliance{}
	return &this
}

// GetDesign returns the Design field value if set, zero value otherwise.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) GetDesign() string {
	if o == nil || IsNil(o.Design) {
		var ret string
		return ret
	}
	return *o.Design
}

// GetDesignOk returns a tuple with the Design field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) GetDesignOk() (*string, bool) {
	if o == nil || IsNil(o.Design) {
		return nil, false
	}
	return o.Design, true
}

// HasDesign returns a boolean if a field has been set.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) HasDesign() bool {
	if o != nil && !IsNil(o.Design) {
		return true
	}

	return false
}

// SetDesign gets a reference to the given string and assigns it to the Design field.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) SetDesign(v string) {
	o.Design = &v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) GetSecurity() string {
	if o == nil || IsNil(o.Security) {
		var ret string
		return ret
	}
	return *o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) GetSecurityOk() (*string, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given string and assigns it to the Security field.
func (o *ManagementV1alpha1EnvironmentSpecCompliance) SetSecurity(v string) {
	o.Security = &v
}

func (o ManagementV1alpha1EnvironmentSpecCompliance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1EnvironmentSpecCompliance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Design) {
		toSerialize["design"] = o.Design
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1EnvironmentSpecCompliance struct {
	value *ManagementV1alpha1EnvironmentSpecCompliance
	isSet bool
}

func (v NullableManagementV1alpha1EnvironmentSpecCompliance) Get() *ManagementV1alpha1EnvironmentSpecCompliance {
	return v.value
}

func (v *NullableManagementV1alpha1EnvironmentSpecCompliance) Set(val *ManagementV1alpha1EnvironmentSpecCompliance) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1EnvironmentSpecCompliance) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1EnvironmentSpecCompliance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1EnvironmentSpecCompliance(val *ManagementV1alpha1EnvironmentSpecCompliance) *NullableManagementV1alpha1EnvironmentSpecCompliance {
	return &NullableManagementV1alpha1EnvironmentSpecCompliance{value: val, isSet: true}
}

func (v NullableManagementV1alpha1EnvironmentSpecCompliance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1EnvironmentSpecCompliance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


