/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogV1alpha1AssetRequestMarketplaceResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1AssetRequestMarketplaceResource{}

// CatalogV1alpha1AssetRequestMarketplaceResource The Marketplace Access Request resource details.
type CatalogV1alpha1AssetRequestMarketplaceResource struct {
	Metadata CatalogV1alpha1AssetRequestMarketplaceResourceMetadata `json:"metadata"`
	Owner *CatalogV1alpha1AssetRequestMarketplaceResourceOwner `json:"owner,omitempty"`
}

type _CatalogV1alpha1AssetRequestMarketplaceResource CatalogV1alpha1AssetRequestMarketplaceResource

// NewCatalogV1alpha1AssetRequestMarketplaceResource instantiates a new CatalogV1alpha1AssetRequestMarketplaceResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1AssetRequestMarketplaceResource(metadata CatalogV1alpha1AssetRequestMarketplaceResourceMetadata) *CatalogV1alpha1AssetRequestMarketplaceResource {
	this := CatalogV1alpha1AssetRequestMarketplaceResource{}
	this.Metadata = metadata
	return &this
}

// NewCatalogV1alpha1AssetRequestMarketplaceResourceWithDefaults instantiates a new CatalogV1alpha1AssetRequestMarketplaceResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1AssetRequestMarketplaceResourceWithDefaults() *CatalogV1alpha1AssetRequestMarketplaceResource {
	this := CatalogV1alpha1AssetRequestMarketplaceResource{}
	return &this
}

// GetMetadata returns the Metadata field value
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) GetMetadata() CatalogV1alpha1AssetRequestMarketplaceResourceMetadata {
	if o == nil {
		var ret CatalogV1alpha1AssetRequestMarketplaceResourceMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) GetMetadataOk() (*CatalogV1alpha1AssetRequestMarketplaceResourceMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) SetMetadata(v CatalogV1alpha1AssetRequestMarketplaceResourceMetadata) {
	o.Metadata = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) GetOwner() CatalogV1alpha1AssetRequestMarketplaceResourceOwner {
	if o == nil || IsNil(o.Owner) {
		var ret CatalogV1alpha1AssetRequestMarketplaceResourceOwner
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) GetOwnerOk() (*CatalogV1alpha1AssetRequestMarketplaceResourceOwner, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given CatalogV1alpha1AssetRequestMarketplaceResourceOwner and assigns it to the Owner field.
func (o *CatalogV1alpha1AssetRequestMarketplaceResource) SetOwner(v CatalogV1alpha1AssetRequestMarketplaceResourceOwner) {
	o.Owner = &v
}

func (o CatalogV1alpha1AssetRequestMarketplaceResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1AssetRequestMarketplaceResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["metadata"] = o.Metadata
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	return toSerialize, nil
}

func (o *CatalogV1alpha1AssetRequestMarketplaceResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogV1alpha1AssetRequestMarketplaceResource := _CatalogV1alpha1AssetRequestMarketplaceResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogV1alpha1AssetRequestMarketplaceResource)

	if err != nil {
		return err
	}

	*o = CatalogV1alpha1AssetRequestMarketplaceResource(varCatalogV1alpha1AssetRequestMarketplaceResource)

	return err
}

type NullableCatalogV1alpha1AssetRequestMarketplaceResource struct {
	value *CatalogV1alpha1AssetRequestMarketplaceResource
	isSet bool
}

func (v NullableCatalogV1alpha1AssetRequestMarketplaceResource) Get() *CatalogV1alpha1AssetRequestMarketplaceResource {
	return v.value
}

func (v *NullableCatalogV1alpha1AssetRequestMarketplaceResource) Set(val *CatalogV1alpha1AssetRequestMarketplaceResource) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1AssetRequestMarketplaceResource) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1AssetRequestMarketplaceResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1AssetRequestMarketplaceResource(val *CatalogV1alpha1AssetRequestMarketplaceResource) *NullableCatalogV1alpha1AssetRequestMarketplaceResource {
	return &NullableCatalogV1alpha1AssetRequestMarketplaceResource{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1AssetRequestMarketplaceResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1AssetRequestMarketplaceResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


