/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
	"time"
)

// checks if the CatalogV1alpha1SubscriptionStateWhen type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1SubscriptionStateWhen{}

// CatalogV1alpha1SubscriptionStateWhen Describes when to execute the scheduled action or when it was executed. Only valid for scheduled actions.
type CatalogV1alpha1SubscriptionStateWhen struct {
	// Time when the scheduled action should execute or was executed.
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// NewCatalogV1alpha1SubscriptionStateWhen instantiates a new CatalogV1alpha1SubscriptionStateWhen object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1SubscriptionStateWhen() *CatalogV1alpha1SubscriptionStateWhen {
	this := CatalogV1alpha1SubscriptionStateWhen{}
	return &this
}

// NewCatalogV1alpha1SubscriptionStateWhenWithDefaults instantiates a new CatalogV1alpha1SubscriptionStateWhen object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1SubscriptionStateWhenWithDefaults() *CatalogV1alpha1SubscriptionStateWhen {
	this := CatalogV1alpha1SubscriptionStateWhen{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CatalogV1alpha1SubscriptionStateWhen) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1SubscriptionStateWhen) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CatalogV1alpha1SubscriptionStateWhen) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *CatalogV1alpha1SubscriptionStateWhen) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o CatalogV1alpha1SubscriptionStateWhen) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1SubscriptionStateWhen) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableCatalogV1alpha1SubscriptionStateWhen struct {
	value *CatalogV1alpha1SubscriptionStateWhen
	isSet bool
}

func (v NullableCatalogV1alpha1SubscriptionStateWhen) Get() *CatalogV1alpha1SubscriptionStateWhen {
	return v.value
}

func (v *NullableCatalogV1alpha1SubscriptionStateWhen) Set(val *CatalogV1alpha1SubscriptionStateWhen) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1SubscriptionStateWhen) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1SubscriptionStateWhen) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1SubscriptionStateWhen(val *CatalogV1alpha1SubscriptionStateWhen) *NullableCatalogV1alpha1SubscriptionStateWhen {
	return &NullableCatalogV1alpha1SubscriptionStateWhen{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1SubscriptionStateWhen) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1SubscriptionStateWhen) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


