/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders{}

// ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders The allowed and sanitization setup of request headers in transactional data
type ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders struct {
	// The regular expressions for request headers that, when matched, will be saved for Business and Consumer Insights
	Show []string `json:"show,omitempty"`
	// The regular expressions for request headers keys that, when matched, will sanitize based off the value regular expression before saving for Business and Consumer Insights
	Sanitize []ManagementV1alpha1TraceabilityAgentSpecConfigRedactionQueryArgumentSanitizeInner `json:"sanitize,omitempty"`
}

// NewManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders instantiates a new ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders() *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders {
	this := ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders{}
	return &this
}

// NewManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeadersWithDefaults instantiates a new ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeadersWithDefaults() *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders {
	this := ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders{}
	return &this
}

// GetShow returns the Show field value if set, zero value otherwise.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) GetShow() []string {
	if o == nil || IsNil(o.Show) {
		var ret []string
		return ret
	}
	return o.Show
}

// GetShowOk returns a tuple with the Show field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) GetShowOk() ([]string, bool) {
	if o == nil || IsNil(o.Show) {
		return nil, false
	}
	return o.Show, true
}

// HasShow returns a boolean if a field has been set.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) HasShow() bool {
	if o != nil && !IsNil(o.Show) {
		return true
	}

	return false
}

// SetShow gets a reference to the given []string and assigns it to the Show field.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) SetShow(v []string) {
	o.Show = v
}

// GetSanitize returns the Sanitize field value if set, zero value otherwise.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) GetSanitize() []ManagementV1alpha1TraceabilityAgentSpecConfigRedactionQueryArgumentSanitizeInner {
	if o == nil || IsNil(o.Sanitize) {
		var ret []ManagementV1alpha1TraceabilityAgentSpecConfigRedactionQueryArgumentSanitizeInner
		return ret
	}
	return o.Sanitize
}

// GetSanitizeOk returns a tuple with the Sanitize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) GetSanitizeOk() ([]ManagementV1alpha1TraceabilityAgentSpecConfigRedactionQueryArgumentSanitizeInner, bool) {
	if o == nil || IsNil(o.Sanitize) {
		return nil, false
	}
	return o.Sanitize, true
}

// HasSanitize returns a boolean if a field has been set.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) HasSanitize() bool {
	if o != nil && !IsNil(o.Sanitize) {
		return true
	}

	return false
}

// SetSanitize gets a reference to the given []ManagementV1alpha1TraceabilityAgentSpecConfigRedactionQueryArgumentSanitizeInner and assigns it to the Sanitize field.
func (o *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) SetSanitize(v []ManagementV1alpha1TraceabilityAgentSpecConfigRedactionQueryArgumentSanitizeInner) {
	o.Sanitize = v
}

func (o ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Show) {
		toSerialize["show"] = o.Show
	}
	if !IsNil(o.Sanitize) {
		toSerialize["sanitize"] = o.Sanitize
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders struct {
	value *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders
	isSet bool
}

func (v NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) Get() *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders {
	return v.value
}

func (v *NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) Set(val *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders(val *ManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) *NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders {
	return &NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders{value: val, isSet: true}
}

func (v NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1TraceabilityAgentSpecConfigRedactionRequestHeaders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


