/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiV1EmbeddedScopedResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1EmbeddedScopedResources{}

// ApiV1EmbeddedScopedResources struct for ApiV1EmbeddedScopedResources
type ApiV1EmbeddedScopedResources struct {
	// The kind of the resource.
	Kind *string `json:"kind,omitempty"`
	// Number of resources.
	Count *int32 `json:"count,omitempty"`
	// The link that can be used to access those resources.
	Link *string `json:"link,omitempty"`
}

// NewApiV1EmbeddedScopedResources instantiates a new ApiV1EmbeddedScopedResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1EmbeddedScopedResources() *ApiV1EmbeddedScopedResources {
	this := ApiV1EmbeddedScopedResources{}
	return &this
}

// NewApiV1EmbeddedScopedResourcesWithDefaults instantiates a new ApiV1EmbeddedScopedResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1EmbeddedScopedResourcesWithDefaults() *ApiV1EmbeddedScopedResources {
	this := ApiV1EmbeddedScopedResources{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ApiV1EmbeddedScopedResources) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1EmbeddedScopedResources) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ApiV1EmbeddedScopedResources) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ApiV1EmbeddedScopedResources) SetKind(v string) {
	o.Kind = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ApiV1EmbeddedScopedResources) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1EmbeddedScopedResources) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ApiV1EmbeddedScopedResources) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ApiV1EmbeddedScopedResources) SetCount(v int32) {
	o.Count = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *ApiV1EmbeddedScopedResources) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1EmbeddedScopedResources) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *ApiV1EmbeddedScopedResources) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *ApiV1EmbeddedScopedResources) SetLink(v string) {
	o.Link = &v
}

func (o ApiV1EmbeddedScopedResources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1EmbeddedScopedResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	return toSerialize, nil
}

type NullableApiV1EmbeddedScopedResources struct {
	value *ApiV1EmbeddedScopedResources
	isSet bool
}

func (v NullableApiV1EmbeddedScopedResources) Get() *ApiV1EmbeddedScopedResources {
	return v.value
}

func (v *NullableApiV1EmbeddedScopedResources) Set(val *ApiV1EmbeddedScopedResources) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1EmbeddedScopedResources) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1EmbeddedScopedResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1EmbeddedScopedResources(val *ApiV1EmbeddedScopedResources) *NullableApiV1EmbeddedScopedResources {
	return &NullableApiV1EmbeddedScopedResources{value: val, isSet: true}
}

func (v NullableApiV1EmbeddedScopedResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1EmbeddedScopedResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


