/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
)

// checks if the CatalogV1alpha1ProductLatestrelease type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1ProductLatestrelease{}

// CatalogV1alpha1ProductLatestrelease Provides newest non-archived release and version. Will be unassigned if no releases exist.
type CatalogV1alpha1ProductLatestrelease struct {
	Name *string `json:"name,omitempty"`
	TagName *string `json:"tagName,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewCatalogV1alpha1ProductLatestrelease instantiates a new CatalogV1alpha1ProductLatestrelease object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1ProductLatestrelease() *CatalogV1alpha1ProductLatestrelease {
	this := CatalogV1alpha1ProductLatestrelease{}
	return &this
}

// NewCatalogV1alpha1ProductLatestreleaseWithDefaults instantiates a new CatalogV1alpha1ProductLatestrelease object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1ProductLatestreleaseWithDefaults() *CatalogV1alpha1ProductLatestrelease {
	this := CatalogV1alpha1ProductLatestrelease{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CatalogV1alpha1ProductLatestrelease) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1ProductLatestrelease) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CatalogV1alpha1ProductLatestrelease) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CatalogV1alpha1ProductLatestrelease) SetName(v string) {
	o.Name = &v
}

// GetTagName returns the TagName field value if set, zero value otherwise.
func (o *CatalogV1alpha1ProductLatestrelease) GetTagName() string {
	if o == nil || IsNil(o.TagName) {
		var ret string
		return ret
	}
	return *o.TagName
}

// GetTagNameOk returns a tuple with the TagName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1ProductLatestrelease) GetTagNameOk() (*string, bool) {
	if o == nil || IsNil(o.TagName) {
		return nil, false
	}
	return o.TagName, true
}

// HasTagName returns a boolean if a field has been set.
func (o *CatalogV1alpha1ProductLatestrelease) HasTagName() bool {
	if o != nil && !IsNil(o.TagName) {
		return true
	}

	return false
}

// SetTagName gets a reference to the given string and assigns it to the TagName field.
func (o *CatalogV1alpha1ProductLatestrelease) SetTagName(v string) {
	o.TagName = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CatalogV1alpha1ProductLatestrelease) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1ProductLatestrelease) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CatalogV1alpha1ProductLatestrelease) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *CatalogV1alpha1ProductLatestrelease) SetVersion(v string) {
	o.Version = &v
}

func (o CatalogV1alpha1ProductLatestrelease) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1ProductLatestrelease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TagName) {
		toSerialize["tagName"] = o.TagName
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableCatalogV1alpha1ProductLatestrelease struct {
	value *CatalogV1alpha1ProductLatestrelease
	isSet bool
}

func (v NullableCatalogV1alpha1ProductLatestrelease) Get() *CatalogV1alpha1ProductLatestrelease {
	return v.value
}

func (v *NullableCatalogV1alpha1ProductLatestrelease) Set(val *CatalogV1alpha1ProductLatestrelease) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1ProductLatestrelease) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1ProductLatestrelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1ProductLatestrelease(val *CatalogV1alpha1ProductLatestrelease) *NullableCatalogV1alpha1ProductLatestrelease {
	return &NullableCatalogV1alpha1ProductLatestrelease{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1ProductLatestrelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1ProductLatestrelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


