/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer{}

// CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer Customer information from the external billing system.
type CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer struct {
	Id string `json:"id"`
}

type _CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer

// NewCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer instantiates a new CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer(id string) *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer {
	this := CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer{}
	this.Id = id
	return &this
}

// NewCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomerWithDefaults instantiates a new CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomerWithDefaults() *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer {
	this := CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer{}
	return &this
}

// GetId returns the Id field value
func (o *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) SetId(v string) {
	o.Id = v
}

func (o CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer := _CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer)

	if err != nil {
		return err
	}

	*o = CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer(varCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer)

	return err
}

type NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer struct {
	value *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer
	isSet bool
}

func (v NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) Get() *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer {
	return v.value
}

func (v *NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) Set(val *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer(val *CatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) *NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer {
	return &NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1SubscriptionInvoiceBillingPaymentTypeCustomCustomer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


