/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource{}

// DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource struct for DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource
type DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource struct {
	// Resource level at which access is being granted.
	Level *string `json:"level,omitempty"`
	// The kind of scoped resources to provide access.
	Kind string `json:"kind"`
	// The name of the scoped resource to provide access to.
	Name string `json:"name"`
	// Set true to allow users to delete the referenced scoped resource.
	AllowDelete *bool `json:"allowDelete,omitempty"`
	// Set true to allow users to update the referenced scoped resource.
	AllowWrite *bool `json:"allowWrite,omitempty"`
}

type _DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource

// NewDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource instantiates a new DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource(kind string, name string) *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource {
	this := DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource{}
	this.Kind = kind
	this.Name = name
	return &this
}

// NewDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResourceWithDefaults instantiates a new DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResourceWithDefaults() *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource {
	this := DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource{}
	return &this
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) SetLevel(v string) {
	o.Level = &v
}

// GetKind returns the Kind field value
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) SetName(v string) {
	o.Name = v
}

// GetAllowDelete returns the AllowDelete field value if set, zero value otherwise.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetAllowDelete() bool {
	if o == nil || IsNil(o.AllowDelete) {
		var ret bool
		return ret
	}
	return *o.AllowDelete
}

// GetAllowDeleteOk returns a tuple with the AllowDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetAllowDeleteOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowDelete) {
		return nil, false
	}
	return o.AllowDelete, true
}

// HasAllowDelete returns a boolean if a field has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) HasAllowDelete() bool {
	if o != nil && !IsNil(o.AllowDelete) {
		return true
	}

	return false
}

// SetAllowDelete gets a reference to the given bool and assigns it to the AllowDelete field.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) SetAllowDelete(v bool) {
	o.AllowDelete = &v
}

// GetAllowWrite returns the AllowWrite field value if set, zero value otherwise.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetAllowWrite() bool {
	if o == nil || IsNil(o.AllowWrite) {
		var ret bool
		return ret
	}
	return *o.AllowWrite
}

// GetAllowWriteOk returns a tuple with the AllowWrite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) GetAllowWriteOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowWrite) {
		return nil, false
	}
	return o.AllowWrite, true
}

// HasAllowWrite returns a boolean if a field has been set.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) HasAllowWrite() bool {
	if o != nil && !IsNil(o.AllowWrite) {
		return true
	}

	return false
}

// SetAllowWrite gets a reference to the given bool and assigns it to the AllowWrite field.
func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) SetAllowWrite(v bool) {
	o.AllowWrite = &v
}

func (o DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	if !IsNil(o.AllowDelete) {
		toSerialize["allowDelete"] = o.AllowDelete
	}
	if !IsNil(o.AllowWrite) {
		toSerialize["allowWrite"] = o.AllowWrite
	}
	return toSerialize, nil
}

func (o *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource := _DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource)

	if err != nil {
		return err
	}

	*o = DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource(varDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource)

	return err
}

type NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource struct {
	value *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource
	isSet bool
}

func (v NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) Get() *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource {
	return v.value
}

func (v *NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) Set(val *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) {
	v.value = val
	v.isSet = true
}

func (v NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) IsSet() bool {
	return v.isSet
}

func (v *NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource(val *DefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) *NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource {
	return &NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource{value: val, isSet: true}
}

func (v NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefinitionsV1alpha1AccessControlListSpecAccessLevelScopedResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


