/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagementV1alpha1ManagedApplicationMarketplace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1ManagedApplicationMarketplace{}

// ManagementV1alpha1ManagedApplicationMarketplace Details about the marketplace Application.
type ManagementV1alpha1ManagedApplicationMarketplace struct {
	// The name of the Marketplace.
	Name string `json:"name"`
	Resource CatalogV1alpha1ApplicationMarketplaceResource `json:"resource"`
}

type _ManagementV1alpha1ManagedApplicationMarketplace ManagementV1alpha1ManagedApplicationMarketplace

// NewManagementV1alpha1ManagedApplicationMarketplace instantiates a new ManagementV1alpha1ManagedApplicationMarketplace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1ManagedApplicationMarketplace(name string, resource CatalogV1alpha1ApplicationMarketplaceResource) *ManagementV1alpha1ManagedApplicationMarketplace {
	this := ManagementV1alpha1ManagedApplicationMarketplace{}
	this.Name = name
	this.Resource = resource
	return &this
}

// NewManagementV1alpha1ManagedApplicationMarketplaceWithDefaults instantiates a new ManagementV1alpha1ManagedApplicationMarketplace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1ManagedApplicationMarketplaceWithDefaults() *ManagementV1alpha1ManagedApplicationMarketplace {
	this := ManagementV1alpha1ManagedApplicationMarketplace{}
	return &this
}

// GetName returns the Name field value
func (o *ManagementV1alpha1ManagedApplicationMarketplace) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1ManagedApplicationMarketplace) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ManagementV1alpha1ManagedApplicationMarketplace) SetName(v string) {
	o.Name = v
}

// GetResource returns the Resource field value
func (o *ManagementV1alpha1ManagedApplicationMarketplace) GetResource() CatalogV1alpha1ApplicationMarketplaceResource {
	if o == nil {
		var ret CatalogV1alpha1ApplicationMarketplaceResource
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1ManagedApplicationMarketplace) GetResourceOk() (*CatalogV1alpha1ApplicationMarketplaceResource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *ManagementV1alpha1ManagedApplicationMarketplace) SetResource(v CatalogV1alpha1ApplicationMarketplaceResource) {
	o.Resource = v
}

func (o ManagementV1alpha1ManagedApplicationMarketplace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1ManagedApplicationMarketplace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["resource"] = o.Resource
	return toSerialize, nil
}

func (o *ManagementV1alpha1ManagedApplicationMarketplace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"resource",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagementV1alpha1ManagedApplicationMarketplace := _ManagementV1alpha1ManagedApplicationMarketplace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagementV1alpha1ManagedApplicationMarketplace)

	if err != nil {
		return err
	}

	*o = ManagementV1alpha1ManagedApplicationMarketplace(varManagementV1alpha1ManagedApplicationMarketplace)

	return err
}

type NullableManagementV1alpha1ManagedApplicationMarketplace struct {
	value *ManagementV1alpha1ManagedApplicationMarketplace
	isSet bool
}

func (v NullableManagementV1alpha1ManagedApplicationMarketplace) Get() *ManagementV1alpha1ManagedApplicationMarketplace {
	return v.value
}

func (v *NullableManagementV1alpha1ManagedApplicationMarketplace) Set(val *ManagementV1alpha1ManagedApplicationMarketplace) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1ManagedApplicationMarketplace) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1ManagedApplicationMarketplace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1ManagedApplicationMarketplace(val *ManagementV1alpha1ManagedApplicationMarketplace) *NullableManagementV1alpha1ManagedApplicationMarketplace {
	return &NullableManagementV1alpha1ManagedApplicationMarketplace{value: val, isSet: true}
}

func (v NullableManagementV1alpha1ManagedApplicationMarketplace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1ManagedApplicationMarketplace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


