/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1APIServiceInstanceReferences type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1APIServiceInstanceReferences{}

// ManagementV1alpha1APIServiceInstanceReferences struct for ManagementV1alpha1APIServiceInstanceReferences
type ManagementV1alpha1APIServiceInstanceReferences struct {
	// Reference to Amplify Central APIService
	ApiService *string `json:"apiService,omitempty"`
	// Computes the APIServiceInstance stage based on the Environment default stage or any override provided in the APIServiceInstance spec.stage property.
	Stage *string `json:"stage,omitempty"`
}

// NewManagementV1alpha1APIServiceInstanceReferences instantiates a new ManagementV1alpha1APIServiceInstanceReferences object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1APIServiceInstanceReferences() *ManagementV1alpha1APIServiceInstanceReferences {
	this := ManagementV1alpha1APIServiceInstanceReferences{}
	return &this
}

// NewManagementV1alpha1APIServiceInstanceReferencesWithDefaults instantiates a new ManagementV1alpha1APIServiceInstanceReferences object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1APIServiceInstanceReferencesWithDefaults() *ManagementV1alpha1APIServiceInstanceReferences {
	this := ManagementV1alpha1APIServiceInstanceReferences{}
	return &this
}

// GetApiService returns the ApiService field value if set, zero value otherwise.
func (o *ManagementV1alpha1APIServiceInstanceReferences) GetApiService() string {
	if o == nil || IsNil(o.ApiService) {
		var ret string
		return ret
	}
	return *o.ApiService
}

// GetApiServiceOk returns a tuple with the ApiService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1APIServiceInstanceReferences) GetApiServiceOk() (*string, bool) {
	if o == nil || IsNil(o.ApiService) {
		return nil, false
	}
	return o.ApiService, true
}

// HasApiService returns a boolean if a field has been set.
func (o *ManagementV1alpha1APIServiceInstanceReferences) HasApiService() bool {
	if o != nil && !IsNil(o.ApiService) {
		return true
	}

	return false
}

// SetApiService gets a reference to the given string and assigns it to the ApiService field.
func (o *ManagementV1alpha1APIServiceInstanceReferences) SetApiService(v string) {
	o.ApiService = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *ManagementV1alpha1APIServiceInstanceReferences) GetStage() string {
	if o == nil || IsNil(o.Stage) {
		var ret string
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1APIServiceInstanceReferences) GetStageOk() (*string, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *ManagementV1alpha1APIServiceInstanceReferences) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given string and assigns it to the Stage field.
func (o *ManagementV1alpha1APIServiceInstanceReferences) SetStage(v string) {
	o.Stage = &v
}

func (o ManagementV1alpha1APIServiceInstanceReferences) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1APIServiceInstanceReferences) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiService) {
		toSerialize["apiService"] = o.ApiService
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1APIServiceInstanceReferences struct {
	value *ManagementV1alpha1APIServiceInstanceReferences
	isSet bool
}

func (v NullableManagementV1alpha1APIServiceInstanceReferences) Get() *ManagementV1alpha1APIServiceInstanceReferences {
	return v.value
}

func (v *NullableManagementV1alpha1APIServiceInstanceReferences) Set(val *ManagementV1alpha1APIServiceInstanceReferences) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1APIServiceInstanceReferences) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1APIServiceInstanceReferences) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1APIServiceInstanceReferences(val *ManagementV1alpha1APIServiceInstanceReferences) *NullableManagementV1alpha1APIServiceInstanceReferences {
	return &NullableManagementV1alpha1APIServiceInstanceReferences{value: val, isSet: true}
}

func (v NullableManagementV1alpha1APIServiceInstanceReferences) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1APIServiceInstanceReferences) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


