/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CatalogV1DocumentResourceState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1DocumentResourceState{}

// CatalogV1DocumentResourceState Current state of the DocumentResource.
type CatalogV1DocumentResourceState struct {
	// The name of the state of the DocumentResource. If the state is \"final\" it means that the DocumentResource can be used in Products or Marketplace settings.
	Name *string `json:"name,omitempty"`
}

// NewCatalogV1DocumentResourceState instantiates a new CatalogV1DocumentResourceState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1DocumentResourceState() *CatalogV1DocumentResourceState {
	this := CatalogV1DocumentResourceState{}
	return &this
}

// NewCatalogV1DocumentResourceStateWithDefaults instantiates a new CatalogV1DocumentResourceState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1DocumentResourceStateWithDefaults() *CatalogV1DocumentResourceState {
	this := CatalogV1DocumentResourceState{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CatalogV1DocumentResourceState) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1DocumentResourceState) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CatalogV1DocumentResourceState) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CatalogV1DocumentResourceState) SetName(v string) {
	o.Name = &v
}

func (o CatalogV1DocumentResourceState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1DocumentResourceState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCatalogV1DocumentResourceState struct {
	value *CatalogV1DocumentResourceState
	isSet bool
}

func (v NullableCatalogV1DocumentResourceState) Get() *CatalogV1DocumentResourceState {
	return v.value
}

func (v *NullableCatalogV1DocumentResourceState) Set(val *CatalogV1DocumentResourceState) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1DocumentResourceState) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1DocumentResourceState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1DocumentResourceState(val *CatalogV1DocumentResourceState) *NullableCatalogV1DocumentResourceState {
	return &NullableCatalogV1DocumentResourceState{value: val, isSet: true}
}

func (v NullableCatalogV1DocumentResourceState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1DocumentResourceState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


