/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus{}

// ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus Provides the current runtime result.
type ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus struct {
	Result *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusResult `json:"result,omitempty"`
}

// NewManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus instantiates a new ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus() *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus {
	this := ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus{}
	return &this
}

// NewManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusWithDefaults instantiates a new ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusWithDefaults() *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus {
	this := ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) GetResult() ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusResult {
	if o == nil || IsNil(o.Result) {
		var ret ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) GetResultOk() (*ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusResult and assigns it to the Result field.
func (o *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) SetResult(v ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatusResult) {
	o.Result = &v
}

func (o ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus struct {
	value *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus
	isSet bool
}

func (v NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) Get() *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus {
	return v.value
}

func (v *NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) Set(val *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus(val *ManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) *NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus {
	return &NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus{value: val, isSet: true}
}

func (v NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1APIServiceInstanceComplianceRuntimeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


