/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1APIServiceSourceDataplaneType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1APIServiceSourceDataplaneType{}

// ManagementV1alpha1APIServiceSourceDataplaneType struct for ManagementV1alpha1APIServiceSourceDataplaneType
type ManagementV1alpha1APIServiceSourceDataplaneType struct {
	// Dataplane type
	Managed *string `json:"managed,omitempty"`
	// Design Repository type
	Design *string `json:"design,omitempty"`
}

// NewManagementV1alpha1APIServiceSourceDataplaneType instantiates a new ManagementV1alpha1APIServiceSourceDataplaneType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1APIServiceSourceDataplaneType() *ManagementV1alpha1APIServiceSourceDataplaneType {
	this := ManagementV1alpha1APIServiceSourceDataplaneType{}
	return &this
}

// NewManagementV1alpha1APIServiceSourceDataplaneTypeWithDefaults instantiates a new ManagementV1alpha1APIServiceSourceDataplaneType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1APIServiceSourceDataplaneTypeWithDefaults() *ManagementV1alpha1APIServiceSourceDataplaneType {
	this := ManagementV1alpha1APIServiceSourceDataplaneType{}
	return &this
}

// GetManaged returns the Managed field value if set, zero value otherwise.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) GetManaged() string {
	if o == nil || IsNil(o.Managed) {
		var ret string
		return ret
	}
	return *o.Managed
}

// GetManagedOk returns a tuple with the Managed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) GetManagedOk() (*string, bool) {
	if o == nil || IsNil(o.Managed) {
		return nil, false
	}
	return o.Managed, true
}

// HasManaged returns a boolean if a field has been set.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) HasManaged() bool {
	if o != nil && !IsNil(o.Managed) {
		return true
	}

	return false
}

// SetManaged gets a reference to the given string and assigns it to the Managed field.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) SetManaged(v string) {
	o.Managed = &v
}

// GetDesign returns the Design field value if set, zero value otherwise.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) GetDesign() string {
	if o == nil || IsNil(o.Design) {
		var ret string
		return ret
	}
	return *o.Design
}

// GetDesignOk returns a tuple with the Design field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) GetDesignOk() (*string, bool) {
	if o == nil || IsNil(o.Design) {
		return nil, false
	}
	return o.Design, true
}

// HasDesign returns a boolean if a field has been set.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) HasDesign() bool {
	if o != nil && !IsNil(o.Design) {
		return true
	}

	return false
}

// SetDesign gets a reference to the given string and assigns it to the Design field.
func (o *ManagementV1alpha1APIServiceSourceDataplaneType) SetDesign(v string) {
	o.Design = &v
}

func (o ManagementV1alpha1APIServiceSourceDataplaneType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1APIServiceSourceDataplaneType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Managed) {
		toSerialize["managed"] = o.Managed
	}
	if !IsNil(o.Design) {
		toSerialize["design"] = o.Design
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1APIServiceSourceDataplaneType struct {
	value *ManagementV1alpha1APIServiceSourceDataplaneType
	isSet bool
}

func (v NullableManagementV1alpha1APIServiceSourceDataplaneType) Get() *ManagementV1alpha1APIServiceSourceDataplaneType {
	return v.value
}

func (v *NullableManagementV1alpha1APIServiceSourceDataplaneType) Set(val *ManagementV1alpha1APIServiceSourceDataplaneType) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1APIServiceSourceDataplaneType) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1APIServiceSourceDataplaneType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1APIServiceSourceDataplaneType(val *ManagementV1alpha1APIServiceSourceDataplaneType) *NullableManagementV1alpha1APIServiceSourceDataplaneType {
	return &NullableManagementV1alpha1APIServiceSourceDataplaneType{value: val, isSet: true}
}

func (v NullableManagementV1alpha1APIServiceSourceDataplaneType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1APIServiceSourceDataplaneType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


