/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1AssetMappingStatusOutputsInnerResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1AssetMappingStatusOutputsInnerResource{}

// ManagementV1alpha1AssetMappingStatusOutputsInnerResource The resources that were impacted with the trigger of asset mapping.
type ManagementV1alpha1AssetMappingStatusOutputsInnerResource struct {
	AssetResource *ManagementV1alpha1AssetMappingStatusOutputsInnerResourceAssetResource `json:"assetResource,omitempty"`
	Stage *ManagementV1alpha1AssetMappingStatusOutputsInnerResourceStage `json:"stage,omitempty"`
}

// NewManagementV1alpha1AssetMappingStatusOutputsInnerResource instantiates a new ManagementV1alpha1AssetMappingStatusOutputsInnerResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1AssetMappingStatusOutputsInnerResource() *ManagementV1alpha1AssetMappingStatusOutputsInnerResource {
	this := ManagementV1alpha1AssetMappingStatusOutputsInnerResource{}
	return &this
}

// NewManagementV1alpha1AssetMappingStatusOutputsInnerResourceWithDefaults instantiates a new ManagementV1alpha1AssetMappingStatusOutputsInnerResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1AssetMappingStatusOutputsInnerResourceWithDefaults() *ManagementV1alpha1AssetMappingStatusOutputsInnerResource {
	this := ManagementV1alpha1AssetMappingStatusOutputsInnerResource{}
	return &this
}

// GetAssetResource returns the AssetResource field value if set, zero value otherwise.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) GetAssetResource() ManagementV1alpha1AssetMappingStatusOutputsInnerResourceAssetResource {
	if o == nil || IsNil(o.AssetResource) {
		var ret ManagementV1alpha1AssetMappingStatusOutputsInnerResourceAssetResource
		return ret
	}
	return *o.AssetResource
}

// GetAssetResourceOk returns a tuple with the AssetResource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) GetAssetResourceOk() (*ManagementV1alpha1AssetMappingStatusOutputsInnerResourceAssetResource, bool) {
	if o == nil || IsNil(o.AssetResource) {
		return nil, false
	}
	return o.AssetResource, true
}

// HasAssetResource returns a boolean if a field has been set.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) HasAssetResource() bool {
	if o != nil && !IsNil(o.AssetResource) {
		return true
	}

	return false
}

// SetAssetResource gets a reference to the given ManagementV1alpha1AssetMappingStatusOutputsInnerResourceAssetResource and assigns it to the AssetResource field.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) SetAssetResource(v ManagementV1alpha1AssetMappingStatusOutputsInnerResourceAssetResource) {
	o.AssetResource = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) GetStage() ManagementV1alpha1AssetMappingStatusOutputsInnerResourceStage {
	if o == nil || IsNil(o.Stage) {
		var ret ManagementV1alpha1AssetMappingStatusOutputsInnerResourceStage
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) GetStageOk() (*ManagementV1alpha1AssetMappingStatusOutputsInnerResourceStage, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given ManagementV1alpha1AssetMappingStatusOutputsInnerResourceStage and assigns it to the Stage field.
func (o *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) SetStage(v ManagementV1alpha1AssetMappingStatusOutputsInnerResourceStage) {
	o.Stage = &v
}

func (o ManagementV1alpha1AssetMappingStatusOutputsInnerResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1AssetMappingStatusOutputsInnerResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssetResource) {
		toSerialize["assetResource"] = o.AssetResource
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource struct {
	value *ManagementV1alpha1AssetMappingStatusOutputsInnerResource
	isSet bool
}

func (v NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource) Get() *ManagementV1alpha1AssetMappingStatusOutputsInnerResource {
	return v.value
}

func (v *NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource) Set(val *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1AssetMappingStatusOutputsInnerResource(val *ManagementV1alpha1AssetMappingStatusOutputsInnerResource) *NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource {
	return &NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource{value: val, isSet: true}
}

func (v NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1AssetMappingStatusOutputsInnerResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


