/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
)

// checks if the ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs{}

// ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs API specs exposed by this workload on this port.
type ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs struct {
	// Array of references to apispecs discovered by the discovery agent. 
	DiscoveredSpecs []string `json:"discoveredSpecs,omitempty"`
}

// NewManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs instantiates a new ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs() *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs {
	this := ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs{}
	return &this
}

// NewManagementV1alpha1MeshWorkloadSpecPortsInnerSpecsWithDefaults instantiates a new ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1MeshWorkloadSpecPortsInnerSpecsWithDefaults() *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs {
	this := ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs{}
	return &this
}

// GetDiscoveredSpecs returns the DiscoveredSpecs field value if set, zero value otherwise.
func (o *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) GetDiscoveredSpecs() []string {
	if o == nil || IsNil(o.DiscoveredSpecs) {
		var ret []string
		return ret
	}
	return o.DiscoveredSpecs
}

// GetDiscoveredSpecsOk returns a tuple with the DiscoveredSpecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) GetDiscoveredSpecsOk() ([]string, bool) {
	if o == nil || IsNil(o.DiscoveredSpecs) {
		return nil, false
	}
	return o.DiscoveredSpecs, true
}

// HasDiscoveredSpecs returns a boolean if a field has been set.
func (o *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) HasDiscoveredSpecs() bool {
	if o != nil && !IsNil(o.DiscoveredSpecs) {
		return true
	}

	return false
}

// SetDiscoveredSpecs gets a reference to the given []string and assigns it to the DiscoveredSpecs field.
func (o *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) SetDiscoveredSpecs(v []string) {
	o.DiscoveredSpecs = v
}

func (o ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiscoveredSpecs) {
		toSerialize["discoveredSpecs"] = o.DiscoveredSpecs
	}
	return toSerialize, nil
}

type NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs struct {
	value *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs
	isSet bool
}

func (v NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) Get() *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs {
	return v.value
}

func (v *NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) Set(val *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs(val *ManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) *NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs {
	return &NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs{value: val, isSet: true}
}

func (v NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1MeshWorkloadSpecPortsInnerSpecs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


