/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CatalogV1DocumentResourceReferencesMarketplaceSettingsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1DocumentResourceReferencesMarketplaceSettingsInner{}

// CatalogV1DocumentResourceReferencesMarketplaceSettingsInner struct for CatalogV1DocumentResourceReferencesMarketplaceSettingsInner
type CatalogV1DocumentResourceReferencesMarketplaceSettingsInner struct {
	// The Marketplace reference.
	Name *string `json:"name,omitempty"`
}

// NewCatalogV1DocumentResourceReferencesMarketplaceSettingsInner instantiates a new CatalogV1DocumentResourceReferencesMarketplaceSettingsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1DocumentResourceReferencesMarketplaceSettingsInner() *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner {
	this := CatalogV1DocumentResourceReferencesMarketplaceSettingsInner{}
	return &this
}

// NewCatalogV1DocumentResourceReferencesMarketplaceSettingsInnerWithDefaults instantiates a new CatalogV1DocumentResourceReferencesMarketplaceSettingsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1DocumentResourceReferencesMarketplaceSettingsInnerWithDefaults() *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner {
	this := CatalogV1DocumentResourceReferencesMarketplaceSettingsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) SetName(v string) {
	o.Name = &v
}

func (o CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner struct {
	value *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner
	isSet bool
}

func (v NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner) Get() *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner {
	return v.value
}

func (v *NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner) Set(val *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner(val *CatalogV1DocumentResourceReferencesMarketplaceSettingsInner) *NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner {
	return &NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner{value: val, isSet: true}
}

func (v NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1DocumentResourceReferencesMarketplaceSettingsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


