/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner{}

// CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner struct for CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner
type CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner struct {
	When *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWhen `json:"when,omitempty"`
	Action *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerAction `json:"action,omitempty"`
}

// NewCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner instantiates a new CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner() *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner {
	this := CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner{}
	return &this
}

// NewCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWithDefaults instantiates a new CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWithDefaults() *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner {
	this := CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner{}
	return &this
}

// GetWhen returns the When field value if set, zero value otherwise.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) GetWhen() CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWhen {
	if o == nil || IsNil(o.When) {
		var ret CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWhen
		return ret
	}
	return *o.When
}

// GetWhenOk returns a tuple with the When field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) GetWhenOk() (*CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWhen, bool) {
	if o == nil || IsNil(o.When) {
		return nil, false
	}
	return o.When, true
}

// HasWhen returns a boolean if a field has been set.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) HasWhen() bool {
	if o != nil && !IsNil(o.When) {
		return true
	}

	return false
}

// SetWhen gets a reference to the given CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWhen and assigns it to the When field.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) SetWhen(v CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerWhen) {
	o.When = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) GetAction() CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerAction {
	if o == nil || IsNil(o.Action) {
		var ret CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) GetActionOk() (*CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerAction, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerAction and assigns it to the Action field.
func (o *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) SetAction(v CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInnerAction) {
	o.Action = &v
}

func (o CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.When) {
		toSerialize["when"] = o.When
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	return toSerialize, nil
}

type NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner struct {
	value *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner
	isSet bool
}

func (v NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) Get() *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner {
	return v.value
}

func (v *NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) Set(val *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner(val *CatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) *NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner {
	return &NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1SubscriptionJobSpecPostExecuteOnSuccessInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


