/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogV1alpha1AssetReferencesEnvironmentRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1AssetReferencesEnvironmentRef{}

// CatalogV1alpha1AssetReferencesEnvironmentRef struct for CatalogV1alpha1AssetReferencesEnvironmentRef
type CatalogV1alpha1AssetReferencesEnvironmentRef struct {
	Kind string `json:"kind"`
	Name *string `json:"name,omitempty"`
}

type _CatalogV1alpha1AssetReferencesEnvironmentRef CatalogV1alpha1AssetReferencesEnvironmentRef

// NewCatalogV1alpha1AssetReferencesEnvironmentRef instantiates a new CatalogV1alpha1AssetReferencesEnvironmentRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1AssetReferencesEnvironmentRef(kind string) *CatalogV1alpha1AssetReferencesEnvironmentRef {
	this := CatalogV1alpha1AssetReferencesEnvironmentRef{}
	this.Kind = kind
	return &this
}

// NewCatalogV1alpha1AssetReferencesEnvironmentRefWithDefaults instantiates a new CatalogV1alpha1AssetReferencesEnvironmentRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1AssetReferencesEnvironmentRefWithDefaults() *CatalogV1alpha1AssetReferencesEnvironmentRef {
	this := CatalogV1alpha1AssetReferencesEnvironmentRef{}
	return &this
}

// GetKind returns the Kind field value
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) SetName(v string) {
	o.Name = &v
}

func (o CatalogV1alpha1AssetReferencesEnvironmentRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1AssetReferencesEnvironmentRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

func (o *CatalogV1alpha1AssetReferencesEnvironmentRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogV1alpha1AssetReferencesEnvironmentRef := _CatalogV1alpha1AssetReferencesEnvironmentRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogV1alpha1AssetReferencesEnvironmentRef)

	if err != nil {
		return err
	}

	*o = CatalogV1alpha1AssetReferencesEnvironmentRef(varCatalogV1alpha1AssetReferencesEnvironmentRef)

	return err
}

type NullableCatalogV1alpha1AssetReferencesEnvironmentRef struct {
	value *CatalogV1alpha1AssetReferencesEnvironmentRef
	isSet bool
}

func (v NullableCatalogV1alpha1AssetReferencesEnvironmentRef) Get() *CatalogV1alpha1AssetReferencesEnvironmentRef {
	return v.value
}

func (v *NullableCatalogV1alpha1AssetReferencesEnvironmentRef) Set(val *CatalogV1alpha1AssetReferencesEnvironmentRef) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1AssetReferencesEnvironmentRef) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1AssetReferencesEnvironmentRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1AssetReferencesEnvironmentRef(val *CatalogV1alpha1AssetReferencesEnvironmentRef) *NullableCatalogV1alpha1AssetReferencesEnvironmentRef {
	return &NullableCatalogV1alpha1AssetReferencesEnvironmentRef{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1AssetReferencesEnvironmentRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1AssetReferencesEnvironmentRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


