/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CatalogV1alpha1SubscriptionBillingPaymentTypeStripe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogV1alpha1SubscriptionBillingPaymentTypeStripe{}

// CatalogV1alpha1SubscriptionBillingPaymentTypeStripe struct for CatalogV1alpha1SubscriptionBillingPaymentTypeStripe
type CatalogV1alpha1SubscriptionBillingPaymentTypeStripe struct {
	Type *string `json:"type,omitempty"`
}

// NewCatalogV1alpha1SubscriptionBillingPaymentTypeStripe instantiates a new CatalogV1alpha1SubscriptionBillingPaymentTypeStripe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogV1alpha1SubscriptionBillingPaymentTypeStripe() *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe {
	this := CatalogV1alpha1SubscriptionBillingPaymentTypeStripe{}
	return &this
}

// NewCatalogV1alpha1SubscriptionBillingPaymentTypeStripeWithDefaults instantiates a new CatalogV1alpha1SubscriptionBillingPaymentTypeStripe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogV1alpha1SubscriptionBillingPaymentTypeStripeWithDefaults() *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe {
	this := CatalogV1alpha1SubscriptionBillingPaymentTypeStripe{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) SetType(v string) {
	o.Type = &v
}

func (o CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe struct {
	value *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe
	isSet bool
}

func (v NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe) Get() *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe {
	return v.value
}

func (v *NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe) Set(val *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe(val *CatalogV1alpha1SubscriptionBillingPaymentTypeStripe) *NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe {
	return &NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe{value: val, isSet: true}
}

func (v NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogV1alpha1SubscriptionBillingPaymentTypeStripe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


