/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagementV1alpha1CredentialStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1CredentialStatus{}

// ManagementV1alpha1CredentialStatus struct for ManagementV1alpha1CredentialStatus
type ManagementV1alpha1CredentialStatus struct {
	// The current status level, indicating progress towards consistency.
	Level string `json:"level"`
	// Reasons for the generated status.
	Reasons []CatalogV1alpha1SubscriptionStatusReasonsInner `json:"reasons,omitempty"`
}

type _ManagementV1alpha1CredentialStatus ManagementV1alpha1CredentialStatus

// NewManagementV1alpha1CredentialStatus instantiates a new ManagementV1alpha1CredentialStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1CredentialStatus(level string) *ManagementV1alpha1CredentialStatus {
	this := ManagementV1alpha1CredentialStatus{}
	this.Level = level
	return &this
}

// NewManagementV1alpha1CredentialStatusWithDefaults instantiates a new ManagementV1alpha1CredentialStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1CredentialStatusWithDefaults() *ManagementV1alpha1CredentialStatus {
	this := ManagementV1alpha1CredentialStatus{}
	return &this
}

// GetLevel returns the Level field value
func (o *ManagementV1alpha1CredentialStatus) GetLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1CredentialStatus) GetLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *ManagementV1alpha1CredentialStatus) SetLevel(v string) {
	o.Level = v
}

// GetReasons returns the Reasons field value if set, zero value otherwise.
func (o *ManagementV1alpha1CredentialStatus) GetReasons() []CatalogV1alpha1SubscriptionStatusReasonsInner {
	if o == nil || IsNil(o.Reasons) {
		var ret []CatalogV1alpha1SubscriptionStatusReasonsInner
		return ret
	}
	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1CredentialStatus) GetReasonsOk() ([]CatalogV1alpha1SubscriptionStatusReasonsInner, bool) {
	if o == nil || IsNil(o.Reasons) {
		return nil, false
	}
	return o.Reasons, true
}

// HasReasons returns a boolean if a field has been set.
func (o *ManagementV1alpha1CredentialStatus) HasReasons() bool {
	if o != nil && !IsNil(o.Reasons) {
		return true
	}

	return false
}

// SetReasons gets a reference to the given []CatalogV1alpha1SubscriptionStatusReasonsInner and assigns it to the Reasons field.
func (o *ManagementV1alpha1CredentialStatus) SetReasons(v []CatalogV1alpha1SubscriptionStatusReasonsInner) {
	o.Reasons = v
}

func (o ManagementV1alpha1CredentialStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1CredentialStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	if !IsNil(o.Reasons) {
		toSerialize["reasons"] = o.Reasons
	}
	return toSerialize, nil
}

func (o *ManagementV1alpha1CredentialStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagementV1alpha1CredentialStatus := _ManagementV1alpha1CredentialStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagementV1alpha1CredentialStatus)

	if err != nil {
		return err
	}

	*o = ManagementV1alpha1CredentialStatus(varManagementV1alpha1CredentialStatus)

	return err
}

type NullableManagementV1alpha1CredentialStatus struct {
	value *ManagementV1alpha1CredentialStatus
	isSet bool
}

func (v NullableManagementV1alpha1CredentialStatus) Get() *ManagementV1alpha1CredentialStatus {
	return v.value
}

func (v *NullableManagementV1alpha1CredentialStatus) Set(val *ManagementV1alpha1CredentialStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1CredentialStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1CredentialStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1CredentialStatus(val *ManagementV1alpha1CredentialStatus) *NullableManagementV1alpha1CredentialStatus {
	return &NullableManagementV1alpha1CredentialStatus{value: val, isSet: true}
}

func (v NullableManagementV1alpha1CredentialStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1CredentialStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


