/*
AMPLIFY Central API v0.347

APIs to manage AMPLIFY Central configuration resources.

API version: 0.347.0
Contact: support@axway.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package amplify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner{}

// ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner struct for ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner
type ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner struct {
	// The Catalog Item subscription spec key. For API type subscriptions, the key needs to be 'profile'.
	Key string `json:"key"`
	// JSON schema to specify data needed from consumers when subscriptions are created.
	Value map[string]interface{} `json:"value"`
}

type _ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner

// NewManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner instantiates a new ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner(key string, value map[string]interface{}) *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner {
	this := ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner{}
	this.Key = key
	this.Value = value
	return &this
}

// NewManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInnerWithDefaults instantiates a new ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInnerWithDefaults() *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner {
	this := ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner{}
	return &this
}

// GetKey returns the Key field value
func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner := _ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner)

	if err != nil {
		return err
	}

	*o = ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner(varManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner)

	return err
}

type NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner struct {
	value *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner
	isSet bool
}

func (v NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) Get() *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner {
	return v.value
}

func (v *NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) Set(val *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner(val *ManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) *NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner {
	return &NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner{value: val, isSet: true}
}

func (v NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementV1alpha1ConsumerSubscriptionDefinitionSpecSchemaPropertiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


